pipeline {
	agent any
	environment {
		SERVER_PORT = '8082'
	}
	
	stages {
		stage('Build Docker Image') {
			steps {
				sh 'docker build -t henrikol/go-calculator:latest ./docker'
			}
		}
		
		stage('Remove old container') {
			when {
				not {
					expression {
						return sh(returnStdout: true, script: 'docker ps -a -f name=go-calculator -q').trim() == ""
					}
				}
			}
			steps {
				sh 'docker stop go-calculator'
				sh 'docker rm go-calculator'
			}
		}
		
		stage('Run Docker Container') {
			steps {
				sh 'docker run --name go-calculator -p ${SERVER_PORT}:8080 -d henrikol/go-calculator:latest'
			}
		}
		
		stage('Gatling Stress Test') {
			steps {
				dir('gatling') {
					sh './gradlew gatlingRun -Dport=${SERVER_PORT}'
				}
			}
			post {
				always {
					gatlingArchive()
				}
			}
		}
	}
}
